In [4]:
## 필요한 데이터를 csv 형식으로 가져오기 위해 필요한 모듈 import
import pandas as pd

## 데이터 읽고 array 형식으로 바꿔서 저장
df_data = pd.read_csv('https://raw.githubusercontent.com/rickiepark/hg-mldl/master/perch_full.csv')
arr_perch_full = df_data.to_numpy()
print(arr_perch_full)

[[ 8.4   2.11  1.41]
 [13.7   3.53  2.  ]
 [15.    3.82  2.43]
 [16.2   4.59  2.63]
 [17.4   4.59  2.94]
 [18.    5.22  3.32]
 [18.7   5.2   3.12]
 [19.    5.64  3.05]
 [19.6   5.14  3.04]
 [20.    5.08  2.77]
 [21.    5.69  3.56]
 [21.    5.92  3.31]
 [21.    5.69  3.67]
 [21.3   6.38  3.53]
 [22.    6.11  3.41]
 [22.    5.64  3.52]
 [22.    6.11  3.52]
 [22.    5.88  3.52]
 [22.    5.52  4.  ]
 [22.5   5.86  3.62]
 [22.5   6.79  3.62]
 [22.7   5.95  3.63]
 [23.    5.22  3.63]
 [23.5   6.28  3.72]
 [24.    7.29  3.72]
 [24.    6.38  3.82]
 [24.6   6.73  4.17]
 [25.    6.44  3.68]
 [25.6   6.56  4.24]
 [26.5   7.17  4.14]
 [27.3   8.32  5.14]
 [27.5   7.17  4.34]
 [27.5   7.05  4.34]
 [27.5   7.28  4.57]
 [28.    7.82  4.2 ]
 [28.7   7.59  4.64]
 [30.    7.62  4.77]
 [32.8  10.03  6.02]
 [34.5  10.26  6.39]
 [35.   11.49  7.8 ]
 [36.5  10.88  6.86]
 [36.   10.61  6.74]
 [37.   10.84  6.26]
 [37.   10.57  6.37]
 [39.   11.14  7.49]
 [39.   11.14  6.  ]
 [39.   12.43  7.35]
 [40.   11.93

In [5]:
## 필요한 모듈 import
import numpy as np

## 데이터 array화
arr_perch_weight = np.array([5.9, 32.0, 40.0, 51.5, 70.0, 100.0, 78.0, 80.0, 85.0, 85.0, 110.0,
       115.0, 125.0, 130.0, 120.0, 120.0, 130.0, 135.0, 110.0, 130.0,
       150.0, 145.0, 150.0, 170.0, 225.0, 145.0, 188.0, 180.0, 197.0,
       218.0, 300.0, 260.0, 265.0, 250.0, 250.0, 300.0, 320.0, 514.0,
       556.0, 840.0, 685.0, 700.0, 700.0, 690.0, 900.0, 650.0, 820.0,
       850.0, 900.0, 1015.0, 820.0, 1100.0, 1000.0, 1100.0, 1000.0,
       1000.0])

In [6]:
## 데이터를 훈련 세트와 테스트 세트로 나눠주기 위한 함수 import
from sklearn.model_selection import train_test_split

## 함수를 사용해 세트 나누기
arr_train_input, arr_test_input, arr_train_target, arr_test_target = train_test_split(
    arr_perch_full, arr_perch_weight, random_state= 42
)

## 배열 모양 확인
print(arr_train_input.shape, arr_test_input.shape)

(42, 3) (14, 3)


In [7]:
## 특성 조합을 만들기 위해 필요한 모듈 import
from sklearn.preprocessing import PolynomialFeatures

## 객체 생성 후 훈련, 특성 조합 함수 예제
c_poly = PolynomialFeatures()
c_poly.fit([[2,3]])

## 특성 조합 확인
print(c_poly.transform([[2,3]]))

[[1. 2. 3. 4. 6. 9.]]


In [10]:
## 맨 앞에 절편을 위한 항을 제거하고 다시 확인 예제
c_poly = PolynomialFeatures(include_bias= False)
c_poly.fit([[2,3]])
print(c_poly.transform([[2,3]]))

[[2. 3. 4. 6. 9.]]


In [12]:
## 훈련 세트 데이터로 교육시키고 특성 조합 진행
c_poly = PolynomialFeatures(include_bias= False)
c_poly.fit(arr_train_input)
arr_train_poly = c_poly.transform(arr_train_input)

## 조합된 특성의 array 모양 확인
print(arr_train_poly.shape)

(42, 9)


In [14]:
## 특성 조합이 어떻게 되는지 확인
c_poly.get_feature_names_out()

array(['x0', 'x1', 'x2', 'x0^2', 'x0 x1', 'x0 x2', 'x1^2', 'x1 x2',
       'x2^2'], dtype=object)

In [15]:
## 테스트 세트도 특성 조합
arr_test_poly = c_poly.transform(arr_test_input)

In [16]:

from sklearn.linear_model import LinearRegression

c_lr = LinearRegression()
c_lr.fit(arr_train_poly, arr_train_target)

print(c_lr.score(arr_train_poly, arr_train_target))

0.9903183436982124


In [17]:
print(c_lr.score(arr_test_poly, arr_test_target))

0.9714559911594145


In [18]:
c_poly_adit = PolynomialFeatures(degree= 5, include_bias= False)

c_poly_adit.fit(arr_train_input)
arr_train_poly = c_poly_adit.transform(arr_train_input)
arr_test_poly = c_poly_adit.transform(arr_test_input)

print(arr_train_poly.shape)

(42, 55)


In [19]:
c_lr.fit(arr_train_poly,arr_train_target)

print(c_lr.score(arr_train_poly, arr_train_target))

0.9999999999996176


In [20]:
print(c_lr.score(arr_test_poly, arr_test_target))

-144.40585108215134
